language: java
jdk:
  - oraclejdk8
  install:
    - "sudo apt-get install oracle-java8-installer"
    - "sudo update-java-alternatives -s java-8-oracle"
    - "export JAVA_HOME=/usr/lib/jvm/java-8-oracle"
